/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.15
 * Generated at: 2018-04-22 16:44:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import carConnection.Carconnect;
import java.sql.Connection;
import carConnection.*;
import java.sql.*;

public final class Payment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body bgcolor=\"#C39BD3195\">\r\n");
      out.write("<form action=\"Bank.jsp\">\r\n");
      out.write("<table border=\"3\" align=\"center\">\r\n");
      out.write("<tr>\r\n");
      out.write("<th colspan=\"3\">Confirm Your Booking</th>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr><th>Route Selected</th><th>Cost Of Travelling</th></tr> \r\n");

try{
	int price=0;
	Connection cn=Carconnect.getCn();
	String rid[]=request.getParameterValues("mini");
	String selection="select place,cost from route where rid=?";
	for(String x:rid){
		PreparedStatement ps=cn.prepareStatement(selection);
		ps.setString(1, x);
		ResultSet rs=ps.executeQuery();
		while(rs.next()){
			price=price+Integer.parseInt(rs.getString(2));
			

      out.write("\r\n");
      out.write("<tr><td>");
      out.print(rs.getString(1) );
      out.write("</td>\r\n");
      out.write("<td>");
      out.print(rs.getString(2) );
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
} 
      out.write("\r\n");
      out.write("\r\n");
} 
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td><b><font color=\"blue\">Total Cost Of Travelling</b></font></td><td><b>");
      out.print(price );
      out.write("</b></td>\r\n");
      out.write("</tr>\r\n");
}catch(Exception e){
	System.out.print(e);
}	
      out.write("\r\n");
      out.write("<tr><td colspan=\"3\" align=\"right\"><input type=\"submit\" value=\"Proceed To Payment Page\"></td></tr>\r\n");
      out.write("<tr><th colspan=\"2\"><a href=Route.jsp>Back To Previous Page</a></th></tr>\r\n");
      out.write("<tr><th colspan=\"2\"><a href=cab.html>Back To Home Page</a></th></tr>\r\n");
      out.write("<tr><th colspan=\"2\"><a href=registration.html>New user ?REGISTER HERE </a></th></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
